<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>API SIMPLE</title>
</head>
<body>
    <h1>Layout principal</h1>
    <nav>
        <ul>
            <?php
            if(isset($_SESSION["userId"]))
            {
                ?>
                <li><a href="index.php?route=disconnect">Disconnect</a></li>
                <li><a href="index.php?route=edit-user">account</a></li>
                <?php
            }else{
                ?>
                <li><a href="index.php?route=read-user">Login</a></li>
                <li><a href="index.php?route=create-user">Register</a></li>
                <?php
            }
            ?>
        </ul>
    </nav>
    <?php
        require $this->template;
    ?>
</body>
</html>