<h2>My account</h2>
<form method="POST" action="index.php?route=edit-user">
    <label for="firstname">Firstname</label>
    <input type="text" name="firstname"/>
    <label for="lastname">Lastname</label>
    <input type="text" name="lastname"/>
    <label for="email">Email</label>
    <input type="email" name="email"/>
    <input type="submit" value="Submit"/>
</form>

<form action="index.php?route=delete-user" method="POST">
    <input type="submit" value="Delete account"/>
</form>

<table>
    <thead>
        <th>
            <td>First Name</td>
            <td>Last Name</td>
            <td>Email</td>
        </th>
    </thead>
    <tbody>
        <tr>
            <?php
            
            if(isset($data["users"])){
                foreach($data["users"] as $user)
                {
                    ?><td><?=$user->getFirstName()?></td>
                    <td><?=$user->getLastName()?></td>
                    <td><?=$user->getEmail()?></td><?php
                }
            }
            
            ?>
        </tr>
    </tbody>
    
</table>